id: P003017
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC244
  title: 'འཇིགས་མེད་རྡོ་རྗེའི་གསོ་རིག་བརྩམས་ཆོས་གཅེས་བསྡུས། '
  author: ''
  volumes:
    099b21fef9574b2e84164449e098b379:
      image_group_id: I2PD18140
      title: ''
      volume_number: 1
      total_pages: 564
