id: P003017
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 10:34:35.185438
source_metadata:
  id: bdr:W1AC244
  title: 'འཇིགས་མེད་རྡོ་རྗེའི་གསོ་རིག་བརྩམས་ཆོས་གཅེས་བསྡུས། '
  author: ''
  volumes:
    099b21fef9574b2e84164449e098b379:
      image_group_id: I2PD18140
      title: ''
      volume_number: 1
      total_pages: 564
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
